Fix migrating users whose username is the beginning of another username
4teamwork/ftw.usermigration pull request #15
Opened 2017-03-29 11:38 UTC by elioschmutz

See #14 for more information.

Closes #14

2017-04-06 07:35 UTC, lukasgraf requested changes
Some minor points, looks good to me otherwise 👍

2017-04-06 07:35 UTC, lukasgraf commented on ftw/usermigration/tests/test_users.py
> +    def test_migrate_user_which_is_a_part_of_another_user_does_not_fail(self):
`test_migrate_userid_which_is_a_substring_of_another_userid`?

2017-04-06 07:35 UTC, lukasgraf commented on setup.py
> +    'plone.api'
Please add a trailing comma after `'plone.api'`

2017-04-06 07:35 UTC, lukasgraf commented on ftw/usermigration/users.py
> +            if not IZODBUserManager.providedBy(plugin):
Please don't sneak refactorings into functional parts of the PR without mentioning them. Ideally, do them in a separate commit.

2017-04-06 08:38 UTC, elioschmutz commented
@lukasgraf 👍  done! I also split the commit into a functional and a refactoring commit.

2017-04-06 10:19 UTC, lukasgraf approved these changes

2017-04-10 14:23 UTC, buchi commented
@elioschmutz looks good to me. Can you fix conflicts in `HISTORY.txt` and rebase?

2017-04-10 14:46 UTC, elioschmutz commented
@buchi 👍

2017-04-10 16:23 UTC, buchi commented on docs/HISTORY.txt
>  - Implement group members migration [elioschmutz]
@elioschmutz Can you add newlines between changelog entries? Should be consistent with the previous ones.

2017-04-12 07:02 UTC, elioschmutz commented
@buchi 👍

2017-04-13 08:50 UTC, merged